name: Release Codepush Build and Deploy

on: 
  push:
    branches:
      - 'release/codepush_**'
jobs:
  codepush-android-build-deploy:
      name: Codepush Android Build and Deploy
      runs-on: ubuntu-latest
      env:
        ACTIONS_OS_NAME: "linux"
        NODE_OPTIONS: --max_old_space_size=8192
        CODEPUSH_KEY_PASSWORD: ${{ secrets.CODEPUSH_API_TOKEN }}
        timeout-minutes: 120
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release/codepush_02
          fetch-depth: 0
      - name: fetch
        run: |
           git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - uses: geertvdc/setup-hub@master
      - name: Configure Git
        run: |
          git config --local user.email "vijay.jeyaraman@cognizant.com"
          git config --local user.name "Vijay Actions"
      - name: create PR
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -f -b jyajiv/example-services:release/codepush_01 -h jyajiv/example-services:release/codepush_02 -m 'Git diff report for release/20.5.0 and release/20.5.0'
          node ./devScripts/createDiffPR.js

  
